### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by gkamaall** [pengrad/java-telegram-bot-api#101]
i add jar file in may project in netbeans but have many errore
why?

Exception in thread "OkHttp Dispatcher" java.lang.AbstractMethodError: com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(Lokhttp3/Response;)V
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pengrad** [comment]
Please try to add other dependencies as well
https://oss.sonatype.org/content/repositories/releases/com/github/pengrad/java-telegram-bot-api/3.1.0/java-telegram-bot-api-3.1.0.pom

I will prepare full jar with dependencies.

But better switch to maven/gradle using

**Comment by pengrad** [comment]
@gkamaall Please, check jar from here
https://github.com/pengrad/java-telegram-bot-api/releases/tag/3.1.0
