### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by gkamaall** [pengrad/java-telegram-bot-api#102]
Exception in thread "OkHttp Dispatcher" java.lang.AbstractMethodError: com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(Lokhttp3/Response;)V
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pengrad** [comment]
You created one, its enough
