### ISSUE TITLE
Intermittent Timeouts on send message

### ISSUE THREAD

**Issue by EvanKnowles** [pengrad/java-telegram-bot-api#146]
I get occasional write timeouts when sending messages:
`Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:56)
	... 84 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 104 more
`

This happens primarily when sending large numbers of messages, which makes me think that it might be me hitting Telegram's throttling, but adding code to sleep between messages doesn't seem to help and I wouldn't have thought that a 429 would show as a Socket Closed.

My bot is constructed with:

`OkHttpClient client = new OkHttpClient.Builder()         .connectTimeout(15, TimeUnit.SECONDS)         .writeTimeout(60, TimeUnit.SECONDS)         .readTimeout(60, TimeUnit.SECONDS)         .build(); 
`

Anything else that I could be doing wrong? Or is it the throttle?

**Comment by pengrad** [comment]
Yes, it doesn't look like a 429. 
I got 429 before and was able to solve it with sleep, but now I can't even simulate it.

Problems with timeouts are normal for Telegram, I often meet them, specially when sending files.
And I can't say that 1 min for read is more than enough. 
Last time I got my tests failed because setWebhook with custom certificate file couldn't finish for 30 and 45 secs  (1 min is ok for now though).

You can try to increase timeout (it's always `readTimeout` for me) or remove it completely `.readTimeout(0, TimeUnit.SECONDS)`

**Comment by EvanKnowles** [comment]
Just for interest sake, catching the exception and trying again just resulted in the Telegram servers sending a bunch of duplicate messages, so it looks like all the calls to their API went through. It definitely re-occurs at the same point when I'm sending a test sequence of messages, so maybe it is some sort of spam throttling happening on their end?

**Comment by EvanKnowles** [comment]
I re-read the docs, and they do confusingly say one message a second and 20 messages a minute. I figured it was a typo and delayed just for the one message a second, but I counted how many messages I sent before getting the time out exceptions and it is indeed exactly 20, over 20s because of my built-in delay.

I then get no response for another around ~40s, so that would fill up the final part of the 20 messages a minute requirement. I'm going to increase my throttle massively and see if that fixes it.

**Comment by EvanKnowles** [comment]
Confirmed, sleeping for remainder of 3s to meet the 20 msgs/minute requirement resulted in no timeouts. Going to implement a rolling throttle over the last 60s on my side to try balance the two throttle requirements.

**Comment by pengrad** [comment]
Thanks for great research! 
Just tested on group and found same, ~40s after 20 messages. 
Then Telegram processes 5 messages and delay for 40s again.
It doesn't apply on sending to single user, which I tested before - can send unlimited.

I wonder why `.readTimeout(60, TimeUnit.SECONDS) ` as your initial setup didn't work. I can send 100 messages with 1min timeout without any interruptions for ~4m30s, which is slightly faster than using 3s sleep :))

Maybe 60s should be default timeout on client?
