### ISSUE TITLE
Failed to connect to api.telegram.org/2001:67c:4e8:f004:0:0:0:9:443

### ISSUE THREAD

**Issue by ZombieTheBest** [pengrad/java-telegram-bot-api#147]
Hello, first of all thanks for this great library!

In the past two days I'm getting this exception randomly when sending/receiving messages:

`java.net.ConnectException: Failed to connect to api.telegram.org/2001:67c:4e8:f004:0:0:0:9:443`

Here's an example of a full-stack trace of the error:

```
12-12-2018 @ 08:00:54 GMT | Exception roundTimer(): java.lang.RuntimeException: java.net.ConnectException: Failed to connect to api.telegram.org/2001:67c:4e8:f004:0:0:0:9:443

java.lang.RuntimeException: java.net.ConnectException: Failed to connect to api.telegram.org/2001:67c:4e8:f004:0:0:0:9:443

        at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:59)

        at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:36)

        at bot.MessageClass.sendMessage(MessageClass.java:198)

        at bot.RoundTime.roundTimer(RoundTime.java:44)

        at bot.Main$3.run(Main.java:52)

        at java.base/java.lang.Thread.run(Thread.java:844)

Caused by: java.net.ConnectException: Failed to connect to api.telegram.org/2001:67c:4e8:f004:0:0:0:9:443

        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)

        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)

        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)

        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)

        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)

        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)

        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)

        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)

        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)

        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)

        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)

        at okhttp3.RealCall.execute(RealCall.java:77)

        at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:56)

        ... 5 more

Caused by: java.net.ConnectException: Network is unreachable (connect failed)

        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)

        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)

        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)

        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)

        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)

        at java.base/java.net.Socket.connect(Socket.java:591)

        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)

        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)

        ... 23 more

```

Is this problem related with the library, with Telegram or with the server connection? 
I'm trying to investigate but I can't find an explanation for this.

Thanks for your time

**Comment by ZombieTheBest** [comment]
Thanks for your answer! I just noticed that I'm getting issues also from my home IP (running code from my PC), so it's definetely not a server issue.

Disabling IPv6 gives me: 
`java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out`

So I used your sintax for okHttpClient:

```
BOT=new TelegramBot.Builder(BOT_TOKEN)
                .okHttpClient(new OkHttpClient.Builder()
                    .readTimeout(60, TimeUnit.SECONDS)
                    .connectTimeout(60, TimeUnit.SECONDS)
                    .build())
                .build();
```

And it seems working (still need more time to confirm of course). 
I still have some questions: why this started 2 days ago? Also, which timeout should I put (60 seconds are maybe to long)?

Thanks again!

**Comment by ZombieTheBest** [comment]
Still getting timeouts:

```
java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
        at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:59)
        at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:41)
        at common.d.a(Unknown Source)
        at common.scontibot.p.c(Unknown Source)
        at common.scontibot.v.a(Unknown Source)
        at common.scontibot.t.a(Unknown Source)
        at common.scontibot.j.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:56)
        ... 7 more
```

**Comment by pengrad** [comment]
Did you check access to api.telegram.org?
`curl https://api.telegram.org/botTOKEN/getMe`

**Comment by nukassel** [comment]
Hi, for me, this problem is also relevant. I am from Russia and its territory is blocked "https://api.telegram.org". I have a proxy domain outside of Russia, I want to specify it as a domain, where should your library send requests, is it possible?

PS this message is made through google translate

**Comment by nukassel** [comment]
I use TelegramBotAdapter.build (token), is there something similar for it?

**Comment by pengrad** [comment]
Result is same `TelegramBot` object, just upgrade to new version of lib if you don't have it

**Comment by nukassel** [comment]
and if there is no possibility to update the library?

**Comment by pengrad** [comment]
then `TelegramBotAdapter.buildCustom(String botToken, OkHttpClient okHttpClient, String apiUrl)`

**Comment by pengrad** [comment]
@nukassel please create another issue, you went too far from original @ZombieTheBest question

**Comment by ZombieTheBest** [comment]
Thanks @pengrad 

So, I've tried to get BOT info using **curl**.

I sent 16 requests, 15 went through with an "ok" response. one of those requests failed with:

`curl: (7) Failed to connect to api.telegram.org port 443: Connection expired`

It also does this in local with another IP, so maybe it's a Telegram server issue. Any idea on how I can force the BOT to use another Telegram server rather the default one?

**Comment by pengrad** [comment]
There is no other "server".
If it happens not always - you can retry failed request

**Comment by ZombieTheBest** [comment]
I confirm I'm getting the exact same issue with my local connection. The problem with that approach is that I would have to rewrite a lot of code as I have all my bots having this issue (even those compiled with older versions of the library). I hope this is a telegram-side issue that will be solved soon. 
Maybe, can the automatic-retry be implemented directly into the library?

**Comment by ZombieTheBest** [comment]
No luck. When I start this BOT it spams something like 3-4 messages to the first admin. I can't get the BOT to start anymore.

Here's my TelegramBot object:

```
            BOT=new TelegramBot.Builder(BOT_TOKEN)
                .okHttpClient(new OkHttpClient.Builder()
                    .readTimeout(5, TimeUnit.SECONDS)
                    .connectTimeout(5, TimeUnit.SECONDS)
                    .addInterceptor(chain -> {
                        Request request = chain.request();
                        Response response = chain.proceed(request);
                        int tryCount = 0;
                        while (!response.isSuccessful() && tryCount < 6) {
                            tryCount++;
                            LOGGER.writeLog("Failed Telegram Request... retrying " + tryCount + "/5");
                            response = chain.proceed(request);
                        }
                        return response;
                    })
                    .build())
                .build();
```

Here's what is printed in console:

```
12-12-2018 18:06:16 GMT+2 @  | Failed Telegram Request... retrying 1/5
Exception in thread "TelegramPool--1001394361336" java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:59)
	at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:41)
	at common.scontibot.Keyboards.menuAutoKeyboard(Keyboards.java:77)
	at common.scontibot.BotInterface.botThread(BotInterface.java:43)
	at common.scontibot.BotInterface$1.run(BotInterface.java:34)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at singlebot.SingleBot.lambda$0(SingleBot.java:246)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:56)
	... 4 more
```

it looks like it does not try more than 1 time and gives an error anyway. BOT stops totally responding after that exception

**Comment by pengrad** [comment]
ok, how about this one :))

```java
.addInterceptor(chain -> {
    Request request = chain.request();
    Response response = null;
    IOException error = new IOException();
    try {
        response = chain.proceed(request);
    } catch (IOException e) {
        error = e;
    }
    int tryCount = 0;
    while ((response == null || !response.isSuccessful()) && tryCount < 6) {
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        tryCount++;
        System.out.println("Retry " + tryCount);
        try {
            response = chain.proceed(request);
        } catch (IOException e) {
            error = e;
        }
    }
    if (response != null) return response;
    else throw error;
})
```

**Comment by pengrad** [comment]
@ZombieTheBest  ?

**Comment by ZombieTheBest** [comment]
Hi, sorry for the late answer. I was actually checking if it was working and it is. 
Right now Telegram stopped giving back timeout errors (so there was definitely a problem from their side), but the solution you provided me worked!

Only thing I can say is that the okhttp3 garbage collector complains about the response left open into the interceptor, but I guess it will clean that automatically.

Thanks a lot for your help!
Keep up the great work!! :)

**Comment by lwx1660677335** [comment]
> @ZombieTheBest？
I need a long video upload code


When I upload a video to around 1 GB, I report an error

![QQ截图20231023201104](https://github.com/pengrad/java-telegram-bot-api/assets/12846588/9149a23c-d917-4ce6-9c7b-e95f78e599c7)
