### ISSUE TITLE
key

### ISSUE THREAD

**Issue by amirhododi** [pengrad/java-telegram-bot-api#18]
Hi 

i use                 bot.sendMessage(102504428, "Message",null,null,null,new ReplyKeyboardMarkup(new String[]{"ok", "cancel"}).oneTimeKeyboard(true));

but message not send to bot

why?

**Comment by pengrad** [comment]
Try to build your bot with TelegramBotAdapter.buildDebug("BOT_TOKEN") and post full log (telegram api answer)

**Comment by amirhododi** [comment]
`package amir.telegrambotapi;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.AsyncTask;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;


import com.pengrad.telegrambot.TelegramBot;
import com.pengrad.telegrambot.TelegramBotAdapter;
import com.pengrad.telegrambot.model.request.Keyboard;
import com.pengrad.telegrambot.model.request.ReplyKeyboardMarkup;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.Reader;
import java.util.List;

// samples https://github.com/pengrad/java-telegram-bot-api

public class MainActivity extends AppCompatActivity {
    TelegramBot bot;
    Keyboard replyKeyboardMarkup;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

         bot = TelegramBotAdapter.build("103257610:AAEMytdV_QzTe_lRL3BvbJYtqqglIOh7T8U");


         replyKeyboardMarkup = new ReplyKeyboardMarkup(
                new String[]{"first row button1", "first row button2"},
                new String[]{"second row button1", "second row button2"})
                .oneTimeKeyboard(true);   // optional
      // optional

        new BOT().execute("");


    }
    private class BOT extends AsyncTask<String, Void, String> {
        @Override
        protected String doInBackground(String... params) {
      //      for (int i = 0; i < 70; i++) {

            try {

                bot.sendMessage(102504428, "Message",null,null,null,new ReplyKeyboardMarkup(new String[]{"ok", "cancel"}).oneTimeKeyboard(true));
                //   bot.sendMessage(102504428, "سلام");



            //    GetUpdatesResponse updatesResponse = bot.getUpdates(0, 0, 10000);

              //  List<Update> updates = updatesResponse.updates();

           //     Log.e("BOT",updates.toString());
           //         Bitmap bmp = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
                 //   ByteArrayOutputStream bos = new ByteArrayOutputStream();
                 //   bmp.compress(Bitmap.CompressFormat.JPEG, 100, bos);
                //    byte[] data = bos.toByteArray();

                  //  bot.sendPhoto(102504428, InputFileBytes.photo(data), "caption", null,null);


              //      byte[] bytes = convert("/sdcard/k.mp3");


                  //  bot.sendVoice(102504428, InputFileBytes.voice(bytes), 3, null, null);


                  //  bot.sendChatAction("@testbootapi", ChatAction.upload_audio);

                } catch (Exception e) {

         //       }
           }





            return null;
        }

        @Override
        protected void onPostExecute(String result) {
        }

        @Override
        protected void onPreExecute() {
        }

        @Override
        protected void onProgressUpdate(Void... values) {
        }
    }
  
}
`

THIS IS MY CODE

**Comment by amirhododi** [comment]
full log
`04-17 11:46:14.476 2386-2522/? I/PackageManager: Package amir.telegrambotapi codePath changed from /data/app/amir.telegrambotapi-2.apk to /data/app/amir.telegrambotapi-1.apk; Retaining data and using new
04-17 11:46:15.771 2386-2522/? W/PackageManager: Code path for pkg : amir.telegrambotapi changing from /data/app/amir.telegrambotapi-2.apk to /data/app/amir.telegrambotapi-1.apk
04-17 11:46:15.771 2386-2522/? W/PackageManager: Resource path for pkg : amir.telegrambotapi changing from /data/app/amir.telegrambotapi-2.apk to /data/app/amir.telegrambotapi-1.apk
04-17 11:46:16.821 2386-2522/? D/PackageManager: Sending to user 0: act=android.intent.action.PACKAGE_REMOVED dat=package:amir.telegrambotapi flg=0x8000000 Bundle[{android.intent.extra.REMOVED_FOR_ALL_USERS=false, android.intent.extra.DATA_REMOVED=false, android.intent.extra.REPLACING=true, android.intent.extra.user_handle=0, android.intent.extra.UID=10261}]
                                                 java.lang.RuntimeException: It's not exception, just print call stack
                                                     at com.android.server.pm.PackageManagerService.sendPackageBroadcast(PackageManagerService.java:7676)
                                                     at com.android.server.pm.PackageManagerService$PackageRemovedInfo.sendBroadcast(PackageManagerService.java:11186)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.doHandleMessage(PackageManagerService.java:953)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.handleMessage(PackageManagerService.java:716)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:176)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
04-17 11:46:16.921 2386-2522/? D/PackageManager: Sending to user 0: act=android.intent.action.PACKAGE_ADDED dat=package:amir.telegrambotapi flg=0x8000000 Bundle[{android.intent.extra.REPLACING=true, android.intent.extra.UID=10261, android.intent.extra.user_handle=0}]
                                                 java.lang.RuntimeException: It's not exception, just print call stack
                                                     at com.android.server.pm.PackageManagerService.sendPackageBroadcast(PackageManagerService.java:7676)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.doHandleMessage(PackageManagerService.java:1005)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.handleMessage(PackageManagerService.java:716)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:176)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
04-17 11:46:16.991 2386-2522/? D/PackageManager: Sending to user 0: act=android.intent.action.PACKAGE_REPLACED dat=package:amir.telegrambotapi flg=0x8000000 Bundle[{android.intent.extra.REPLACING=true, android.intent.extra.UID=10261, android.intent.extra.user_handle=0}]
                                                 java.lang.RuntimeException: It's not exception, just print call stack
                                                     at com.android.server.pm.PackageManagerService.sendPackageBroadcast(PackageManagerService.java:7676)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.doHandleMessage(PackageManagerService.java:1009)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.handleMessage(PackageManagerService.java:716)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:176)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
04-17 11:46:17.121 25929-25929/? D/Event: No subscribers registered for event class de.greenrobot.event.i
04-17 11:46:17.511 2386-2522/? D/PackageManager: Sending to user 0: act=android.intent.action.MY_PACKAGE_REPLACED flg=0x8000000 pkg=amir.telegrambotapi Bundle[{android.intent.extra.user_handle=0}]
                                                 java.lang.RuntimeException: It's not exception, just print call stack
                                                     at com.android.server.pm.PackageManagerService.sendPackageBroadcast(PackageManagerService.java:7676)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.doHandleMessage(PackageManagerService.java:1012)
                                                     at com.android.server.pm.PackageManagerService$PackageHandler.handleMessage(PackageManagerService.java:716)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:176)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
04-17 11:46:18.891 26432-26432/? D/CapabilityManagerService: The package(amir.telegrambotapi) updated
04-17 11:46:22.106 2386-2498/? D/BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:amir.telegrambotapi flg=0x8000010 (has extras) }
04-17 11:46:23.171 2386-2498/? D/BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:amir.telegrambotapi flg=0x8000010 (has extras) }
04-17 11:46:23.211 2386-2498/? D/ECS_EnterpriseContainerService: <<< Intent data is   >>> : package:amir.telegrambotapi
04-17 11:46:23.211 2386-2498/? D/ECS_EnterpriseContainerService: <<< Intent data is   >>> : package:amir.telegrambotapi
04-17 11:46:23.616 1939-2054/? I/SurfaceFlinger: id=1124 createSurf (1x1),1 flag=404, uelegrambot
04-17 11:46:24.461 2386-2528/? I/CrashAnrDetector: onPackageUpdateFinished : amir.telegrambotapi
04-17 11:46:25.996 26525-26560/? D/Retrofit: (ReflectiveTypeAdapterFactory.java:136)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
                                                 at com.google.gson.Gson.getAdapter(Gson.java:407)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
                                                 at com.google.gson.Gson.getAdapter(Gson.java:407)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
                                                 at com.google.gson.Gson.getAdapter(Gson.java:407)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
                                                 at com.google.gson.Gson.getAdapter(Gson.java:407)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
                                                 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
                                                 at com.google.gson.Gson.getAdapter(Gson.java:407)
                                                 at com.google.gson.Gson.toJson(Gson.java:644)
                                                 at com.google.gson.Gson.toJson(Gson.java:631)
                                                 at com.google.gson.Gson.toJson(Gson.java:586)
                                                 at com.google.gson.Gson.toJson(Gson.java:566)
                                                 at com.pengrad.telegrambot.model.request.Keyboard.toString(Keyboard.java:15)
                                                 at retrofit.RequestBuilder.setArguments(RequestBuilder.java:312)
                                             	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.jav
04-17 11:46:25.996 26525-26560/? D/Retrofit: a:298)
                                                 at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                 at $Proxy0.sendMessage(Native Method)
                                                 at com.pengrad.telegrambot.TelegramBot.sendMessage(TelegramBot.java:47)
                                                 at amir.telegrambotapi.MainActivity$BOT.doInBackground(MainActivity.java:53)
                                                 at amir.telegrambotapi.MainActivity$BOT.doInBackground(MainActivity.java:46)
                                                 at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                 at java.lang.Thread.run(Thread.java:841)
04-17 11:46:26.601 1939-2083/? I/SurfaceFlinger: id=1124 Removed uelegrambot (3/5)
04-17 11:46:26.601 1939-24720/? I/SurfaceFlinger: id=1124 Removed uelegrambot (-2/5)
04-17 11:46:30.321 26710-26710/? I/SmartCardBroadcastReceiver: foundMatchingVendorPackage - Checking for amir.telegrambotapi
04-17 11:46:33.161 24949-26813/? D/PkgBroadcastIntentOp: Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=amir.telegrambotapi
04-17 11:46:33.791 24949-26813/? D/WearableController: Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=amir.telegrambotapi
04-17 11:46:34.231 24949-26832/? D/gH_MetricsDatabase: 0 metrics were deleted when clearing package amir.telegrambotapi.
04-17 11:46:37.196 3441-3441/? I/SAPackageEventReceiver: App amir.telegrambotapi was removed.
04-17 11:46:37.196 3441-3441/? D/SAPackageEventReceiver: unregisterService : amir.telegrambotapi
04-17 11:46:37.226 3441-3441/? D/SAPlatformUtils: AccessPermission of SAP FW is deleted! - amir.telegrambotapi
04-17 11:46:37.476 26962-26962/? I/Gear2PluginReceiver: onReceive ACTION_PACKAGE_REMOVED called pkg :amir.telegrambotapi
04-17 11:46:42.831 25501-25501/? E/HMPackageReceiver: This package will be replaced = amir.telegrambotapi
04-17 11:46:42.866 25501-25501/? I/HMPackageBroadcastReceiver: forReplacing = true, intent = Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:amir.telegrambotapi flg=0x8000010 cmp=com.samsung.android.hostmanager/.pm.HMPackageBroadcastReceiver (has extras) }
04-17 11:46:43.141 27214-27214/? I/PackageControlReceiver: forReplacing=true intent=Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:amir.telegrambotapi flg=0x8000010 cmp=com.samsung.android.app.watchmanager/com.samsung.android.app.twatchmanager.receiver.PackageControlReceiver (has extras) }
04-17 11:46:43.141 27214-27214/? D/PackageControlReceiver: Uninstalled Package :amir.telegrambotapi
04-17 11:46:43.141 27214-27214/? D/PackageControlReceiver:  removeBlockedPackage [amir.telegrambotapi]
04-17 11:46:49.186 2786-2786/? I/HomeSyncInstallReceiver: Package Added : amir.telegrambotapi
04-17 11:46:49.281 27363-27363/? D/Event: No subscribers registered for event class de.greenrobot.event.i
04-17 11:46:49.331 27412-27412/? D/[FileShare][Server]: ServerBroadcastReceiver : onReceive: android.intent.action.PACKAGE_ADDED // package:amir.telegrambotapi
04-17 11:46:54.151 27699-27699/? I/SmartCardBroadcastReceiver: foundMatchingVendorPackage - Checking for amir.telegrambotapi
04-17 11:46:54.456 27711-27723/? I/Icing.InternalIcingCorporaProvider: Updating corpora: A: amir.telegrambotapi, C: MAYBE
04-17 11:46:55.841 24949-27816/? D/PkgBroadcastIntentOp: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=amir.telegrambotapi
04-17 11:46:56.261 24949-27816/? D/WearableController: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=amir.telegrambotapi
04-17 11:46:56.446 24949-27837/? D/k: Processing package: amir.telegrambotapi
04-17 11:46:56.501 24949-27837/? D/GassUtils: Found app info for package amir.telegrambotapi:1. Hash: ca9baeaf8f1713b1e1aa2175cf74991e86cc9b94505a871db13a9e5d8a3b5b68
04-17 11:46:56.501 24949-27837/? D/k: Found info for package amir.telegrambotapi in db.
04-17 11:46:58.176 27846-27846/? I/Finsky: [1] com.google.android.finsky.utils.ay.run(2302): Package state data is missing for amir.telegrambotapi
04-17 11:47:00.561 3441-3441/? I/SAPackageEventReceiver: App amir.telegrambotapi was installed.
04-17 11:47:00.566 3441-3441/? D/SAPackageEventReceiver: registerService : amir.telegrambotapi
04-17 11:47:03.771 25501-25501/? D/HMPackageBroadcastReceiver: isWatchApp(amir.telegrambotapi) = false
04-17 11:47:03.836 25501-25501/? D/HMPackageBroadcastReceiver: onReceive(), amir.telegrambotapi is installed, requesting to sync...
04-17 11:47:05.581 3441-3441/? W/SAPackageEventReceiver: [amir.telegrambotapi] has been removed. We can stop sending intent.
04-17 11:47:09.741 27363-27363/? D/Event: No subscribers registered for event class de.greenrobot.event.i
04-17 11:47:12.706 24949-28524/? D/PkgBroadcastIntentOp: Received broadcast action=android.intent.action.PACKAGE_REPLACED and uri=amir.telegrambotapi
04-17 11:47:12.741 24949-28525/? D/k: Processing package: amir.telegrambotapi
04-17 11:47:12.916 24949-28525/? D/GassUtils: Found app info for package amir.telegrambotapi:1. Hash: ca9baeaf8f1713b1e1aa2175cf74991e86cc9b94505a871db13a9e5d8a3b5b68
04-17 11:47:12.921 24949-28525/? D/k: Found info for package amir.telegrambotapi in db.
04-17 11:47:17.141 25501-25501/? D/HMPackageBroadcastReceiver: Updated package: amir.telegrambotapi
04-17 11:47:17.371 28693-28705/? I/System.out: package:amir.telegrambotapi
`

**Comment by amirhododi** [comment]
can send my full example?

**Comment by pengrad** [comment]
Try 1.3.3 version, just uploaded

**Comment by pengrad** [comment]
Success?
