### ISSUE TITLE
TelegramBotClient.java  - java.lang.NullPointerException

### ISSUE THREAD

**Issue by lmdsystems** [pengrad/java-telegram-bot-api#184]
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:45)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pengrad** [comment]
Check exception in your callback's `onResponse` code please
