### ISSUE TITLE
crash cause of retrofit.RetrofitError

### ISSUE THREAD

**Issue by HaDiSs277** [pengrad/java-telegram-bot-api#20]
unable to start activity ComponentInfo{com.example.hadist.sharetext/com.example.hadist.sharetext.MainActivity}: retrofit.RetrofitError

 it crash and show this error

**Comment by pengrad** [comment]
Every unsuccessful request throws this exception. 
You can build Bot with this method `TelegramBotAdapter.buildDebug("BOT_TOKEN")` and see in log whats happened.

**Comment by pengrad** [comment]
But, try 1.3.3 version first

**Comment by pengrad** [comment]
Ok?

**Comment by HaDiSs277** [comment]
"But, try 1.3.3 version first"
i tried but it crasheed with same error again..

**Comment by HaDiSs277** [comment]
i wrote this;"
 TelegramBot bot = TelegramBotAdapter.buildDebug("MY_BOT_TOKEN");
        Log.i("LOG", "is okay?:"+bot.getMe().isOk());"

and again...

  Caused by: retrofit.RetrofitError
                                                                                    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
                                                                                    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                                                    at $Proxy0.getMe(Native Method)
                                                                                    at com.pengrad.telegrambot.TelegramBot.getMe(TelegramBot.java:39)
                                                                                    at com.example.oive.myapplication.MainActivity.onCreate(MainActivity.java:28)

**Comment by pengrad** [comment]
This is only part of error log. Don't filter it.
I think you have NetworkOnMainThreadException

**Comment by HaDiSs277** [comment]
this is full error:

FATAL EXCEPTION: main
                                                                                Process: com.example.oive.myapplication, PID: 15314
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.oive.myapplication/com.example.oive.myapplication.MainActivity}: retrofit.RetrofitError
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:155)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
                                                                                 Caused by: retrofit.RetrofitError
                                                                                    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
                                                                                    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                                    at $Proxy0.sendMessage(Unknown Source)
                                                                                    at com.pengrad.telegrambot.TelegramBot.sendMessage(TelegramBot.java:43)
                                                                                    at com.example.oive.myapplication.MainActivity.onCreate(MainActivity.java:28)
                                                                                    at android.app.Activity.performCreate(Activity.java:5958)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:155) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
                                                                                 Caused by: android.os.NetworkOnMainThreadException
                                                                                    at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1155)
                                                                                    at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
                                                                                    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                                    at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                                    at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
                                                                                    at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:236)
                                                                                    at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
                                                                                    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
                                                                                    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
                                                                                    at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                                    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                                                    at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68)
                                                                                    at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37)
                                                                                    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                                                                                    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) 
                                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
                                                                                    at $Proxy0.sendMessage(Unknown Source) 
                                                                                    at com.pengrad.telegrambot.TelegramBot.sendMessage(TelegramBot.java:43) 
                                                                                    at com.example.oive.myapplication.MainActivity.onCreate(MainActivity.java:28) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5958) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:155) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by pengrad** [comment]
As i said, android.os.NetworkOnMainThreadException.
You should run in inside AsyncTask or other background thread

**Comment by HaDiSs277** [comment]
thank you so much i ran it in async task  and show me these lines:
04-21 19:53:38.985 22156-22190/com.example.oive.myapplication D/Retrofit: ---> HTTP POST https://api.telegram.org/bot1157691249:AAHQONvsiXqx98amkpcTfKAU_4m6myqDhGE/sendMessage
04-21 19:53:38.985 22156-22190/com.example.oive.myapplication D/Retrofit: Content-Type: application/x-www-form-urlencoded; charset=UTF-8
04-21 19:53:38.985 22156-22190/com.example.oive.myapplication D/Retrofit: Content-Length: 30
04-21 19:53:38.985 22156-22190/com.example.oive.myapplication D/Retrofit: chat_id=%40HaDiSs&text=djfgsdj
04-21 19:53:38.985 22156-22190/com.example.oive.myapplication D/Retrofit: ---> END HTTP (30-byte body)
04-21 19:53:39.005 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfofornet+,hn 16(0x6170692e74656c),sn(),hints(known),family 0,flags 4
04-21 19:53:39.005 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfofornet-, err=8
04-21 19:53:39.005 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfofornet+,hn 16(0x6170692e74656c),sn(),hints(known),family 0,flags 1024
04-21 19:53:39.005 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfofornet-, pass to proxy
04-21 19:53:39.005 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfo_proxy+
04-21 19:53:39.005 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfo_proxy get netid:0
04-21 19:53:39.005 22156-22191/com.example.oive.myapplication I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: TEST SBA LA.BF.1.1.1_RB1 AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.012 + c1105519 + c_apilogging ()
                                                                            OpenGL ES Shader Compiler Version: E031.25.03.00
                                                                            Build Date: 01/23/15 Fri
                                                                            Local Branch: 
                                                                            Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.012
                                                                            Local Patches: NONE
                                                                            Reconstruct Branch: NOTHING
04-21 19:53:39.235 22156-22190/com.example.oive.myapplication D/libc: [NET] android_getaddrinfo_proxy-, success
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: <--- HTTP 401 https://api.telegram.org/bot1157691249:AAHQONvsiXqx98amkpcTfKAU_4m6myqDhGE/sendMessage (2156ms)
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: : HTTP/1.1 401 Unauthorized
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: Connection: keep-alive
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: Content-Length: 67
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: Content-Type: application/json
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: Date: Thu, 21 Apr 2016 15:23:41 GMT
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: Server: nginx/1.9.1
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: X-Android-Received-Millis: 1461252221150
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: X-Android-Response-Source: NETWORK 401
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: X-Android-Sent-Millis: 1461252219820
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: {"ok":false,"error_code":401,"description":"[Error]: Unauthorized"}
04-21 19:53:41.145 22156-22190/com.example.oive.myapplication D/Retrofit: <--- END HTTP (67-byte body)

**Comment by HaDiSs277** [comment]
i am sure that this token is true and it's for my bot .
 but i dont know why it said "Unauthorized"

**Comment by pengrad** [comment]
Cause you should use chatId as integer, not nickname. 
To get it you should write message to your bot via telegram app and then receive it through getUpdates.

**Comment by HaDiSs277** [comment]
what's your mean about getUpdates's parameters(offset,limit,timeout) ?

**Comment by pengrad** [comment]
Null, null, null

**Comment by HaDiSs277** [comment]
oh thank you so muuuchhh!!!!
it workes!
sorry i have new question ! how can i get  my channel chat id? 
"To get it you should write message to your bot via telegram app and then receive it through getUpdates. "  it got me the chat id between Me and MY_BOT

**Comment by pengrad** [comment]
Just use channel name like this "@mychannel"

**Comment by HaDiSs277** [comment]
name no! user name :) 
thank you  so much
