### ISSUE TITLE
Can't import or build (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by lotusexpeditor** [pengrad/java-telegram-bot-api#205]
Can't import or build (java.lang.NoClassDefFoundError)

When I try to build my project with the jar on the release page I get following error and when I try to build  java-telegram-bot-api I get the error on my next post.

javac 1.8.0_252 (OpenJDK) (Ubuntu 16.04.6)

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/pengrad/telegrambot/request/BaseRequest
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.pengrad.telegrambot.request.BaseRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

**Comment by lotusexpeditor** [comment]
I have tried to build it with  javac 1.8.0_252 (OpenJDK)  (Ubuntu 16.04.6)

./gradlew --stacktrace --scan build

> Task :library:test

com.pengrad.telegrambot.passport.decrypt.Base64Test > testDecodeTelegramPrivateKey FAILED
    java.lang.NullPointerException at Base64Test.java:168

com.pengrad.telegrambot.PaymentsTest > answerPreCheckoutQueryError FAILED
    java.lang.ExceptionInInitializerError at PaymentsTest.java:20
        Caused by: java.lang.NumberFormatException at PaymentsTest.java:20

com.pengrad.telegrambot.PaymentsTest > answerShippingQuery FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.PaymentsTest > answerPreCheckoutQuery FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.PaymentsTest > answerShippingQueryError FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.PaymentsTest > sendInvoice FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.PaymentsTest > testSuccessfulPayment FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.login.CheckTelegramAuthTest > login FAILED
    java.lang.NullPointerException at CheckTelegramAuthTest.java:21

com.pengrad.telegrambot.TelegramBotTest > getChatMember FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > setChatStickerSet FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > sendMessageToChannel FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > uploadStickerFile FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > sendLocation FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > preMessageEntity FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > editMessageMedia FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > promoteChatMember FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > deleteChatPhoto FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > sendVideoNoteFile FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > getGameHighScores FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > setGameScore FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > setStickerSetThumb FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > answerInline FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > multipartNonAscii FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > decryptPassport FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

com.pengrad.telegrambot.TelegramBotTest > deleteChatStickerSet FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getStickerSet FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > chosenInlineResult FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > botClientError FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > editMessageReplyMarkup FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setPassportDataErrors FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > unpinChatMessage FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setChatPhoto FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setChatTitle FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > pollAnswer FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > testResponseParameters FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > toWebhookResponse FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > forwardMessage FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > editMessageLiveLocation FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > underlineStrikethroughMessageEntity FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > testAsyncCallback FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendMediaGroup FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setStickerPositionInSet FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setWebhook FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getChat FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getFile FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendChatAction FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > stopMessageLiveLocation FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendAudio FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendPhoto FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendVenue FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendVideo FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendVoice FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > addStickerToSet FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > pinChatMessage FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getMe FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > exportChatInviteLink FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendMessageToChannelId FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setMyCommands FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setChatAdministratorCustomTitle FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getWebhookInfo FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getChatAdministrators FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > answerCallback FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setChatPermissions FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendContact FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendMessage FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > deleteMessage FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > editMessageText FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getUpdates FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > deleteStickerFromSet FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > loginButton FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getChatMembersCount FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > deleteWebhook FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendPollWithKeyboard FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > underlineStrikethroughMarkdown FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendDice FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendGame FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendPoll FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > restrictChatMember FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > createNewStickerSet FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendDocument FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendAnimation FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > unbanChatMember FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendVideoNote FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > leaveChat FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > editMessageCaption FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > stopPoll FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > setChatDescription FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > getUserProfilePhotos FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > kickChatMember FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > createSetAndAddStickerTgs FAILED
    java.lang.NoClassDefFoundError at null:-1

com.pengrad.telegrambot.TelegramBotTest > sendSticker FAILED
    java.lang.NoClassDefFoundError at null:-1

109 tests completed, 91 failed

> Task :library:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:test'.
> There were failing tests. See the report at: file:///home/lotus/Desktop/eebe/java-telegram-bot-api/library/build/reports/tests/test/index.html

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':library:test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/lotus/Desktop/eebe/java-telegram-bot-api/library/build/reports/tests/test/index.html
        at org.gradle.api.tasks.testing.AbstractTestTask.handleTestFailures(AbstractTestTask.java:614)
        at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:485)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:612)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 22s
