### ISSUE TITLE
 java.lang.NoSuchMethodError: 'void okhttp3.internal.platform.Platform.log(int, java.lang.String, java.lang.Throwable)

### ISSUE THREAD

**Issue by Flole998** [pengrad/java-telegram-bot-api#210]
I'm getting this error quite often and after that it's impossible for the bot to receive any additional messages:
```
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: 'void okhttp3.internal.platform.Platform.log(int, java.lang.String, java.lang.Throwable)'
        at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:59)
        at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:47)
        at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:45)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I am using okhttp aswell so I have the following dependencies in my pom.xml:
```
		<!-- https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp -->
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.8.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp-urlconnection -->
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp-urlconnection</artifactId>
			<version>4.8.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.squareup.okio/okio -->
		<dependency>
			<groupId>com.squareup.okio</groupId>
			<artifactId>okio</artifactId>
			<version>2.7.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.squareup.okhttp3/logging-interceptor -->
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>logging-interceptor</artifactId>
			<version>4.8.0</version>
		</dependency>
```

Is this a conflict between my dependencies and this libraries dependencies? How could this be resolved?

**Comment by pengrad** [comment]
Yes, very likely it is a conflict. 
I will check tomorrow and prepare a fix release with new okhttp or updated logger.
Thanks for reporting!

**Comment by Flole998** [comment]
I just checked the relevant parts of the code and I think I can get around it if I do a `bot.setUpdatesListener(updates -> {...}, e -> { e.printStackTrace(); });`? That way the failing code is never called as far as I can see....

**Comment by pengrad** [comment]
Correct!
Setting exception handler will prevent calls to logger.
This should be good a workaround for now
