### ISSUE TITLE
okhttp3 - Update listener failure

### ISSUE THREAD

**Issue by MarkoPaul0** [pengrad/java-telegram-bot-api#227]
I have a bot running for long periods of time, it reacts to simple commands and sometimes publishes msgs to a channel. On rare occasions, maybe once every few days, I see the following failure.
```
okhttp3.internal.platform.Platform.log()                                              INFO:  Update listener failure
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:354)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:226)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

The problem with this is that this exception is seemingly caught by OKHTTP, logged, but then it doesn't actually seem to handle it, since after that I am no longer able to receive commands or publish msgs to a channel.
Would there be any ways for my code to get notified of that exception so I could handle it? Maybe you would have advice on how to prevent that exception from happening in the first place?

**Comment by pengrad** [comment]
It's normal case when your bot doesn't receive any updates.
There is `ExceptionHandler` which will receive this error if you pass it to `setUpdatesListener(UpdatesListener listener, ExceptionHandler exceptionHandler)`.
But logging is actually handling of exception, and then it should proceed with new getUpdates request.
You also can pass custom `GetUpdates` request to `setUpdatesListener` with increased timeout, this may decrease chances of timeout exception.

**Comment by MarkoPaul0** [comment]
Perfect, thank you for the quick reply.
