### ISSUE TITLE
Unable to get Message object if Update received from channel

### ISSUE THREAD

**Issue by RamDurgaSai** [pengrad/java-telegram-bot-api#231]
Bot receiving Updates in **personal chats and groups**
but in the case of **channel** , **Message** is **null**

 Output 
**Personal or Group Chats**

> A new message from RamDurgaSai is Hey Hi

**Updates from channel**

> Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException: update.message() must not be null
	at Ramu$main$1.process(Ramu.kt:18)
	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:71)
	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:48)
	at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:52)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Here's my code
```
import com.pengrad.telegrambot.TelegramBot
import com.pengrad.telegrambot.request.GetUpdates
import com.pengrad.telegrambot.UpdatesListener
import com.pengrad.telegrambot.model.Message
import com.pengrad.telegrambot.model.Update
import com.pengrad.telegrambot.request.SendMessage
import com.pengrad.telegrambot.response.SendResponse

internal object Ramu {
    @JvmStatic
    fun main(args: Array<String>) {
        val bot_token = "MY BOT TOKEN"
        val bot = TelegramBot(bot_token)
        bot.setUpdatesListener { updates ->
        val update: Update = updates[0]
        //System.out.println(update);
        val message: Message = update.message()
        println("A new message from " + message.from().firstName() + " is " + message.text())
        UpdatesListener.CONFIRMED_UPDATES_ALL
        }
    }
}```

**Comment by mircoianese** [comment]
For channels the message object is in: `update.channelPost()`

So do a simple check if `update.channelPost() != null`
