### ISSUE TITLE
Can't create TelegramBot object in 5.1.0 (NoSuchFieldError: Companion in okhttp3)

### ISSUE THREAD

**Issue by Flameish** [pengrad/java-telegram-bot-api#236]
The same code works in 5.0.1 but when upgrading to 5.1.0 it crashes.
```
Exception in thread "main" java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:71)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.pengrad.telegrambot.TelegramBot$Builder.client(TelegramBot.java:139)
	at com.pengrad.telegrambot.TelegramBot$Builder.<init>(TelegramBot.java:96)
	at com.pengrad.telegrambot.TelegramBot.<init>(TelegramBot.java:32)
	at bots.Telegram.<init>(Telegram.java:64)
```

**Comment by Flameish** [comment]
It was a dependency conflict on my part.
