### ISSUE TITLE
java.io.EOFException: \n not found: size=0 content=…

### ISSUE THREAD

**Issue by evnaresh** [pengrad/java-telegram-bot-api#29]
Hi,
   When I try getting updates or when trying to send text messages or images, at intermittent intervals, the following exception generated (The application communicates with the bot over an authenticated proxy):
Caused by: java.io.IOException: unexpected end of stream on null
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:199)
	at okhttp3.internal.io.RealConnection.createTunnel(RealConnection.java:251)
	at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:175)
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at okhttp3.RealCall.getResponse(RealCall.java:240)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:50)
	... 4 more
Caused by: java.io.EOFException: \n not found: size=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	... 18 more

       Any pointers on how to resolve the issue?

**Comment by pengrad** [comment]
I dont know how to resolve it. 
But there is probably some error in your proxy. 
https://github.com/square/okhttp/issues/1517
