### ISSUE TITLE
canSendAudios NoSuchMethodError

### ISSUE THREAD

**Issue by zeahouse** [pengrad/java-telegram-bot-api#333]
com.github.pengrad:java-telegram-bot-api:6.7.0

```
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: com.pengrad.telegrambot.model.ChatPermissions.canSendAudios(Z)Lcom/pengrad/telegrambot/model/ChatPermissions;
        at classes.ContentFilter.RestrictGroupUser(ContentFilter.java:806)
        at classes.ContentFilter.Filter(ContentFilter.java:187)
        at classes.ContentFilter.<init>(ContentFilter.java:42)
        at classes.Bot.lambda$start$0(Bot.java:173)
```

**Comment by pengrad** [comment]
Could it be your build problem? Like you are referencing new version but linking old one <6.5.0 without such method
