### ISSUE TITLE
Exception with business connection 

### ISSUE THREAD

**Issue by funsstudy** [pengrad/java-telegram-bot-api#386]
com.pengrad.telegrambot.TelegramException: java.io.IOException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 5765886655 at line 2 column 173 path $.result[0].business_connection.user_chat_id
	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onFailure(UpdatesHandler.java:96)
	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onFailure(UpdatesHandler.java:54)
	at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:59)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 5765886655 at line 2 column 173 path $.result[0].business_connection.user_chat_id
	at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:58)
	... 4 more

**Comment by pengrad** [comment]
Fixed in 7.7
