### ISSUE TITLE
Failure to execute "TelegramBot bot = TelegramBotAdapter.build(token);"

### ISSUE THREAD

**Issue by menasheh** [pengrad/java-telegram-bot-api#51]
Failed to execute "TelegramBot bot = TelegramBotAdapter.build(token);"

Am I missing a dependency from a third-party source not mentioned in the readme?

Stack Trace:
`Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/Interceptor
	at SampleBot.main(SampleBot.java:13)
Caused by: java.lang.ClassNotFoundException: okhttp3.Interceptor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
`

**Comment by pengrad** [comment]
There is  dependency in lib `compile 'com.squareup.okhttp3:okhttp:3.3.1'`.
Maybe you imported not correctly.

**Comment by menasheh** [comment]
Your Readme suggests that a valid way to import your API is as a jar resource file.  I didn't see anything about that line mentioned.

**Comment by gkamaall** [comment]
Exception in thread "OkHttp Dispatcher" java.lang.AbstractMethodError: com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(Lokhttp3/Response;)V
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
